spring:
  application:
    name: zhibaopayment

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

